export const CONVERSATION_CREATED = "CONVERSATION_CREATED"
export const CONVERSATION_UPDATED = "CONVERSATION_UPDATED"
export const ADDED_TO_CONVERSATION = "ADDED_TO_CONVERSATION"
export const REMOVE_FROM_CONVERSATION = "REMOVE_FROM_CONVERSATION"

export const MESSAGE_SENT = "MESSAGE_SENT"
export const MESSAGE_EDITED = "MESSAGE_EDITED"
